# Generated by Django 4.2.7 on 2023-11-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskdate', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='taskdate',
        ),
    ]
