# Generated by Django 4.2.7 on 2023-12-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_task_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assign',
            field=models.CharField(default='Sayali', max_length=30),
        ),
    ]
