# Generated by Django 4.2.7 on 2023-12-01 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_task_date_alter_task_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 1)),
        ),
    ]
