# Generated by Django 4.2.7 on 2023-12-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(verbose_name='13-12-2023'),
        ),
    ]
