# Generated by Django 4.2.7 on 2023-12-02 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_remove_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dd',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
